QOL
frmscoe/rule-executer pull request #4
Opened 2023-06-22 12:42 UTC by kawaki-san

Check if ruleConfig is not null/undefined
Log status of services after calling creating db manager
Utilise utility fns in frms-coe-lib

2023-06-22 13:49 UTC, johanfol requested changes

2023-06-22 13:49 UTC, johanfol commented on src/controllers/execute.ts
> +  const ruleConfig = unwrap<RuleConfig>(sRuleConfig);
when reading code this would be quite annoying for me as I don't know what this method does... Then when checking out the code and not seeing any code documentation on the "unwrap" helper method makes it impossible for me to approve this.

2023-06-22 13:49 UTC, johanfol commented on src/helpers/determineOutcome.ts
> +const withBands = (bands: Band[], value: number, ruleResult: RuleResult) => {
what does "withBands" mean?

2023-06-22 13:49 UTC, johanfol commented on src/helpers/determineOutcome.ts
> +      ruleResult = withBands(bands, value, ruleResult);
I did not think the length of this method was too long, and also don't think that the piece that was removed make sense on its own, so not sure what we gain to remove this code into a method, other than making the code less readable.

2023-06-22 13:49 UTC, johanfol commented on src/index.ts
> +  loggerService.log(JSON.stringify(databaseManager.isReadyCheck()));
nice catch!

2023-06-22 13:49 UTC, johanfol commented on src/controllers/execute.ts
> +    return '';
instead of return '' here, we could throw an error. If this rule is not in the networkmap, might as well error out. 
```suggestion
    throw new Error(`Rule ${ruleRes.id} not found in network map`);
```

2023-06-22 13:49 UTC, johanfol commented on src/controllers/execute.ts
> +      throw new Error('Rule processor configuration invalid');
```suggestion
      throw new Error(`Rule ${ruleRes.id} processor configuration invalid`);
```

2023-06-22 13:49 UTC, johanfol commented on src/helpers/determineOutcome.ts
> +  const { bands /*, parameters, case: ruleCase */ } = ruleConfig.config;
Why this notation instead of 
```suggestion
  const bands /*, parameters, case: ruleCase */ = ruleConfig.config.bands;
```

2023-06-22 14:31 UTC, kawaki-san commented on src/controllers/execute.ts
> +  const ruleConfig = unwrap<RuleConfig>(sRuleConfig);
So we add docs or scratch?

2023-06-22 14:35 UTC, kawaki-san commented on src/helpers/determineOutcome.ts
> +const withBands = (bands: Band[], value: number, ruleResult: RuleResult) => {
Some rules will have `bands`, some will have `cases`. The evaluation of each should be different (by my understanding). 
`determineOutcome()` should handle each scenario

2023-06-22 14:46 UTC, kawaki-san commented on src/helpers/determineOutcome.ts
> +  const { bands /*, parameters, case: ruleCase */ } = ruleConfig.config;
Purely cosmetic (and less typing for the lazy :D). It's mainly so we don't repeat ourselves in the future since this function will also need to use `case`.

Ultimately, it's:
```js
const {bands, parameters} = ruleConfig.config;
```

vs

```js
const bands = ruleConfig.config.bands
const parameters = ruleConfig.config.parameters
....
```
Do you prefer the latter?

2023-06-22 14:46 UTC, kawaki-san commented on src/helpers/determineOutcome.ts
> +      ruleResult = withBands(bands, value, ruleResult);
Wouldn't we need to extract it into a separate fn later on anyhow when we get to implementing cased outcome logic?

2023-06-22 21:08 UTC, johanfol commented on src/controllers/execute.ts
> +  const ruleConfig = unwrap<RuleConfig>(sRuleConfig);
Yes please.

2023-06-22 21:10 UTC, johanfol commented on src/controllers/execute.ts
> +  const ruleConfig = unwrap<RuleConfig>(sRuleConfig);
on VSCode there's an extension called "document this" - not sure if you've got something similar in vim, but quite handy.

2023-06-22 21:12 UTC, johanfol commented on src/helpers/determineOutcome.ts
> +const withBands = (bands: Band[], value: number, ruleResult: RuleResult) => {
Not sure how we're going to handle it yet. It could very well be a different determineBandedOutcome method. Get your point, but YAGNI could be at stake ;) If you write the other determineBandedOutcome logic then maybe it would make more sense, but right now I don't know what that's going to look like, so now we just have a method with a meaningless name "withBands"... lol

2023-06-22 21:14 UTC, johanfol commented on src/helpers/determineOutcome.ts
> +      ruleResult = withBands(bands, value, ruleResult);
who knows. If we get there, maybe. But if we have 1 method calling 3 other methods, might as well have 3 different determineOutcome functions altogether, and let the rule decide. IDK

2023-06-23 08:35 UTC, kawaki-san commented on src/controllers/execute.ts
> +  const ruleConfig = unwrap<RuleConfig>(sRuleConfig);
There's probably a plugin for it on vim. I'll find it. Thank you

2023-06-23 08:57 UTC, kawaki-san commented on src/helpers/determineOutcome.ts
> +      ruleResult = withBands(bands, value, ruleResult);
> who knows. If we get there, maybe. But if we have 1 method calling 3 other methods, might as well have 3 different determineOutcome functions altogether, and let the rule decide. IDK

I'd like it that way as well, but the only thing that deterred me from that impl was the thought that we'd run into a having to pass more functions to `handleTransaction()`? one for bands another for cases? I think we should keep it in one function like it was before, since we're taking in the ruleConfig in its entirety in `determineOutcome`

2023-06-23 08:58 UTC, kawaki-san commented
Closing this in favour of #5

2023-06-23 08:58 UTC, closed without merging