FIX: Err handling
frmscoe/rule-executer pull request #5
Opened 2023-06-22 17:13 UTC by cshezi

Error handling, fixed prettier and
changed how to get rule cfg early exit

2023-06-22 21:39 UTC, johanfol commented
Most changes on here is in another open PR - only change on determineOutcome function in here doesn't exist on the other branch - so either do the change in that branch, or wait for that merge to come through, then merge main back into your branch to sort out conflicts. Best suggestion is apply the determineOutcome changes to the other open branch. 
https://github.com/frmscoe/rule-executer/pull/4

2023-06-23 09:18 UTC, johanfol requested changes

2023-06-23 09:18 UTC, johanfol commented on src/controllers/execute.ts
> +    return ctx;
add ctx.status = 500

2023-06-23 09:18 UTC, johanfol commented on src/helpers/determineOutcome.ts
> +  if (ruleConfig.config.bands && ruleConfig.config.case) {
why should both bands && case be configured? Shouldn't this be || ?

2023-06-23 09:24 UTC, cshezi commented on src/helpers/determineOutcome.ts
> +  if (ruleConfig.config.bands && ruleConfig.config.case) {
On this condition we are checking if both exist in the configure which I believe is correct logic to handle this case

2023-06-23 09:34 UTC, johanfol commented on src/helpers/determineOutcome.ts
> +  if (ruleConfig.config.bands && ruleConfig.config.case) {
but both won't exist for rules. config will always either be bands or case, never both

2023-06-23 10:04 UTC, cshezi commented on src/controllers/execute.ts
> +    ctx.status = 500;
Changes have been make

2023-06-23 10:08 UTC, johanfol approved these changes

2023-06-23 10:09 UTC, merged